version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: biblioteca-postgres
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: p@ssw0rd!@#
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: